#!/usr/bin/env bash
# GMT on Docker(godocker)
# Author: maxubuntu@gmail.com

## specify GMT version. Latest is 5.4.3
GMT_VERSION=5.4.3

## specify an absolute path(e.g. /home/maxsolar/gmt-figures)
SHARED_FOLDER=$PWD

source ~/.gmtrc 2>/dev/null


## functions
function check_shared_folder() {
    if [ x"$SHARED_FOLDER" == "x" ]; then
        echo "no shared folder detected."
        exit 1;
    else
       if [ -d "$SHARED_FOLDER" ]; then
           export DIR=$(basename "$SHARED_FOLDER")
       else
           echo "$SHARED_FOLDER" is not a directory.
           exit 1;
       fi
    fi
    export MOUNTER="$SHARED_FOLDER:/root/$DIR"
}

function check_gmt_versions() {
    version_list=(5.4.3 5.2.1 4.5.6 4.5.1 4.2.0)
    checker=
    for ver in ${version_list[*]}; do
        if [ "$ver" == "$GMT_VERSION" ]; then
            checker=yes
            break;
        fi
    done
    if [ "$checker" != "yes" ]; then
        echo "$GMT_VERSION is not valid."
        echo "valid versions: ${version_list[*]}"
        exit 2;
    fi
}

function chowner() {
    docker run --rm -v $MOUNTER \
               gmt:$GMT_VERSION chown -R $(id -u):$(id -g) /root/$DIR
}

check_gmt_versions 
if [ x"$1" == "x" ]; then
    check_shared_folder && docker rm -f gmt-$GMT_VERSION
    docker run -it --hostname gmt-$GMT_VERSION --name gmt-$GMT_VERSION \
               -v $MOUNTER \
               gmt:$GMT_VERSION && chowner
else
    docker run --rm gmt:$GMT_VERSION "$@"
fi
